/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_BASIC_PB_H_INCLUDED
#define PB_BASIC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 功能码定义 */
typedef enum _FunCode {
    FunCode_FUNC_UNKNOWN = 0, /* 未知/无效操作（保留） */
    FunCode_FUNC_READ = 1, /* 读取操作 */
    FunCode_FUNC_WRITE = 2, /* 写入操作 */
    FunCode_FUNC_CONFIG = 3, /* 配置操作 */
    FunCode_FUNC_CALIBRATE = 4, /* 校准操作 */
    FunCode_FUNC_RESET = 5, /* 重置操作 */
    FunCode_FUNC_STATUS = 6 /* 状态查询 */
} FunCode;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _FunCode_MIN FunCode_FUNC_UNKNOWN
#define _FunCode_MAX FunCode_FUNC_STATUS
#define _FunCode_ARRAYSIZE ((FunCode)(FunCode_FUNC_STATUS+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
