/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ernc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MSG_AncOff, MSG_AncOff, AUTO)


PB_BIND(MSG_EncOff, MSG_EncOff, AUTO)


PB_BIND(MSG_RncOff, MSG_RncOff, AUTO)


PB_BIND(MSG_CheckMod, MSG_CheckMod, AUTO)


PB_BIND(MSG_ANCControl, MSG_ANCControl, AUTO)


PB_BIND(MSG_RncRefresh, MSG_RncRefresh, AUTO)


PB_BIND(MSG_SpeakerCheck, MSG_SpeakerCheck, AUTO)


PB_BIND(MSG_TranFuncFlag, MSG_TranFuncFlag, AUTO)


PB_BIND(MSG_BypassMode, MSG_BypassMode, AUTO)


PB_BIND(MSG_Alpha, MSG_Alpha, AUTO)


PB_BIND(MSG_Set1, MSG_Set1, AUTO)


PB_BIND(MSG_CalibrationAmp, MSG_CalibrationAmp, 2)


PB_BIND(MSG_CalibrationOther, MSG_CalibrationOther, AUTO)


PB_BIND(MsgRequestResponse, MsgRequestResponse, 2)





