/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ERNC_praram.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MSG_ChannelNumber, MSG_ChannelNumber, AUTO)


PB_BIND(MSG_ChannelAmplitude, MSG_ChannelAmplitude, AUTO)


PB_BIND(MSG_ChannelSwitch, MSG_ChannelSwitch, AUTO)


PB_BIND(MSG_CheckMod, MSG_CheckMod, AUTO)


PB_BIND(MSG_AncSwitch, MSG_AncSwitch, AUTO)


PB_BIND(MSG_VehicleState, MSG_VehicleState, AUTO)


PB_BIND(MSG_TranFuncFlag, MSG_TranFuncFlag, AUTO)


PB_BIND(MSG_TranFuncState, MSG_TranFuncState, AUTO)


PB_BIND(MSG_FilterRanges, MSG_FilterRanges, AUTO)


PB_BIND(MSG_SystemRanges, MSG_SystemRanges, AUTO)


PB_BIND(MSG_OrderFlag, MSG_OrderFlag, AUTO)


PB_BIND(MSG_Order2Params, MSG_Order2Params, AUTO)


PB_BIND(MSG_Order4Params, MSG_Order4Params, AUTO)


PB_BIND(MSG_Order6Params, MSG_Order6Params, AUTO)


PB_BIND(MSG_AlphaParams, MSG_AlphaParams, AUTO)


PB_BIND(MSG_FreqDivision, MSG_FreqDivision, AUTO)


PB_BIND(MSG_Thresholds, MSG_Thresholds, AUTO)


PB_BIND(MsgRequestResponse, MsgRequestResponse, AUTO)







